//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.261
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyPlaner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 255, 128")]
        public global::System.Drawing.Color COLOR_LECTURES {
            get {
                return ((global::System.Drawing.Color)(this["COLOR_LECTURES"]));
            }
            set {
                this["COLOR_LECTURES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128, 255, 255")]
        public global::System.Drawing.Color COLOR_EXERCISES {
            get {
                return ((global::System.Drawing.Color)(this["COLOR_EXERCISES"]));
            }
            set {
                this["COLOR_EXERCISES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 42, 42")]
        public global::System.Drawing.Color COLOR_TUTORIALS {
            get {
                return ((global::System.Drawing.Color)(this["COLOR_TUTORIALS"]));
            }
            set {
                this["COLOR_TUTORIALS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128, 255, 128")]
        public global::System.Drawing.Color COLOR_INTERNSHIPS {
            get {
                return ((global::System.Drawing.Color)(this["COLOR_INTERNSHIPS"]));
            }
            set {
                this["COLOR_INTERNSHIPS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color COLOR_FONT {
            get {
                return ((global::System.Drawing.Color)(this["COLOR_FONT"]));
            }
            set {
                this["COLOR_FONT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.925")]
        public float COLOR_BRIGHTNESSFACTOR {
            get {
                return ((float)(this["COLOR_BRIGHTNESSFACTOR"]));
            }
            set {
                this["COLOR_BRIGHTNESSFACTOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 192, 0")]
        public global::System.Drawing.Color COLOR_SELECTED {
            get {
                return ((global::System.Drawing.Color)(this["COLOR_SELECTED"]));
            }
            set {
                this["COLOR_SELECTED"] = value;
            }
        }
    }
}
