//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18010
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Studyplaner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightSlateGray")]
        public global::System.Drawing.Color USER_COLOR_BACKGROUND {
            get {
                return ((global::System.Drawing.Color)(this["USER_COLOR_BACKGROUND"]));
            }
            set {
                this["USER_COLOR_BACKGROUND"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color USER_COLOR_LECTURE {
            get {
                return ((global::System.Drawing.Color)(this["USER_COLOR_LECTURE"]));
            }
            set {
                this["USER_COLOR_LECTURE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color USER_COLOR_EXERCISE {
            get {
                return ((global::System.Drawing.Color)(this["USER_COLOR_EXERCISE"]));
            }
            set {
                this["USER_COLOR_EXERCISE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color USER_COLOR_INTERNSHIP {
            get {
                return ((global::System.Drawing.Color)(this["USER_COLOR_INTERNSHIP"]));
            }
            set {
                this["USER_COLOR_INTERNSHIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color USER_COLOR_TUTORIAL {
            get {
                return ((global::System.Drawing.Color)(this["USER_COLOR_TUTORIAL"]));
            }
            set {
                this["USER_COLOR_TUTORIAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool USER_LOGGING_ENABLED {
            get {
                return ((bool)(this["USER_LOGGING_ENABLED"]));
            }
            set {
                this["USER_LOGGING_ENABLED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("log.txt")]
        public string USER_LOGGING_PATH {
            get {
                return ((string)(this["USER_LOGGING_PATH"]));
            }
            set {
                this["USER_LOGGING_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkOrange")]
        public global::System.Drawing.Color USER_COLOR_CUSTOM {
            get {
                return ((global::System.Drawing.Color)(this["USER_COLOR_CUSTOM"]));
            }
            set {
                this["USER_COLOR_CUSTOM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool USER_LOGGING_TOCONSOLE {
            get {
                return ((bool)(this["USER_LOGGING_TOCONSOLE"]));
            }
            set {
                this["USER_LOGGING_TOCONSOLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool USER_LOGGING_TOFILE {
            get {
                return ((bool)(this["USER_LOGGING_TOFILE"]));
            }
            set {
                this["USER_LOGGING_TOFILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool USER_LOGGING_WRITETIME {
            get {
                return ((bool)(this["USER_LOGGING_WRITETIME"]));
            }
            set {
                this["USER_LOGGING_WRITETIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string USER_DATAPATH {
            get {
                return ((string)(this["USER_DATAPATH"]));
            }
            set {
                this["USER_DATAPATH"] = value;
            }
        }
    }
}
